{{-- @phase 6.1 Prospective infaq allocation policy --}}
@extends('layouts.app',['pageTitle'=>'Kebijakan Alokasi Infak'])
@section('content')
<div class="v610-page-head"><div><span class="eyebrow">KEBIJAKAN ALOKASI</span><h1>Atur pembagian Infak Umum.</h1><p>Versi baru hanya berlaku untuk infak umum yang diverifikasi setelah perubahan. Infak khusus tetap 100% sesuai tujuan pemberi.</p></div><span class="v610-status is-info">Versi {{ $policy->version }}</span></div>
<nav class="v610-tabs"><a href="{{ route('admin.infaq.index') }}">Penerimaan</a><a href="{{ route('admin.infaq.realisations.index') }}">Realisasi</a><a class="active" href="{{ route('admin.infaq.policy.edit') }}">Kebijakan alokasi</a><a href="{{ route('admin.infaq.reports.index') }}">Arsip laporan</a></nav>
<section class="card"><form class="stack" method="post" action="{{ route('admin.infaq.policy.update') }}" data-percentage-group>@csrf @method('PUT')
@php($values=$policy->items->mapWithKeys(fn($item)=>[$item->category=>$item->basis_points/100]))
<div class="v610-form-grid"><label>Pembinaan/honor ustadz (%)<input type="number" name="teacher_development" min="0" max="100" value="{{ old('teacher_development',$values['teacher_development'] ?? 40) }}" required></label><label>Program yayasan (%)<input type="number" name="foundation_operations" min="0" max="100" value="{{ old('foundation_operations',$values['foundation_operations'] ?? 30) }}" required></label><label>Teknologi (%)<input type="number" name="technology" min="0" max="100" value="{{ old('technology',$values['technology'] ?? 20) }}" required></label><label>Beasiswa (%)<input type="number" name="scholarship" min="0" max="100" value="{{ old('scholarship',$values['scholarship'] ?? 10) }}" required></label><label class="span-2">Alasan perubahan<textarea name="reason" rows="3" minlength="8" required>{{ old('reason') }}</textarea></label></div>
<div class="section-head"><div><span>Total alokasi</span><strong class="v610-percentage-total" data-percentage-total>100%</strong></div><button class="button primary" type="submit" data-confirm-message="Kebijakan baru hanya berlaku untuk transaksi berikutnya. Simpan versi baru?">Simpan versi baru</button></div></form></section>
@endsection
