{{-- @phase 6.1 Immutable monthly infaq reports --}}
@extends('layouts.app',['pageTitle'=>'Arsip Laporan Infak'])
@section('content')
<div class="v610-page-head"><div><span class="eyebrow">ARSIP BULANAN</span><h1>Kunci laporan sebagai jejak yang tidak berubah.</h1><p>Kesalahan arsip diperbaiki melalui jurnal koreksi periode berikutnya, bukan dengan membuka laporan lama.</p></div></div>
<nav class="v610-tabs">@if(auth()->user()->hasAnyRole(['superadmin','institution_admin']))<a href="{{ route('admin.infaq.index') }}">Penerimaan</a>@endif<a href="{{ route('admin.infaq.realisations.index') }}">Realisasi</a>@if(auth()->user()->hasPermission('infaq.policy.manage'))<a href="{{ route('admin.infaq.policy.edit') }}">Kebijakan alokasi</a>@endif<a class="active" href="{{ route('admin.infaq.reports.index') }}">Arsip laporan</a></nav>
@if(auth()->user()->hasPermission('infaq.report.manage'))<section class="card"><form class="v610-toolbar" method="post" action="{{ route('admin.infaq.reports.store') }}">@csrf<label>Periode laporan<input type="month" name="period" max="{{ now()->format('Y-m') }}" required></label><button class="button primary" type="submit" data-confirm-message="Laporan yang dikunci tidak dapat dibuka kembali. Lanjutkan?">Kunci laporan</button></form></section>@endif
@if(auth()->user()->hasPermission('infaq.report.manage'))<section class="card"><div class="section-head"><div><h2>Jurnal koreksi</h2><p class="hint">Catat koreksi pada periode berjalan; arsip sumber tetap utuh.</p></div></div><form class="v610-form-grid" method="post" action="{{ route('admin.infaq.reports.correction') }}">@csrf<label>Periode yang dikoreksi<input type="month" name="source_period" max="{{ now()->format('Y-m') }}" required></label><label>Kategori<select name="category"><option value="teacher_development">Pembinaan/honor ustadz</option><option value="foundation_operations">Program yayasan</option><option value="technology">Teknologi</option><option value="scholarship">Beasiswa</option></select></label><label>Nominal bertanda<input type="number" name="amount" step="1000" required><small>Gunakan nilai negatif untuk debit, positif untuk kredit.</small></label><label>Alasan koreksi<textarea name="reason" minlength="20" required></textarea></label><button class="button secondary" type="submit" data-confirm-message="Catat jurnal koreksi tanpa mengubah arsip lama?">Catat koreksi</button></form></section>@endif
<section class="card"><div class="v610-worklist">@forelse($reports as $report)<article class="v610-workitem"><div><h3>{{ \Illuminate\Support\Carbon::createFromFormat('Y-m',$report->period)->translatedFormat('F Y') }}</h3><small>Dikunci {{ $report->locked_at?->translatedFormat('d M Y H:i') }} · checksum {{ substr($report->checksum,0,12) }}…</small></div><span class="v610-status is-success">Arsip terkunci</span></article>@empty<p class="empty">Belum ada laporan bulanan yang dikunci.</p>@endforelse</div></section>
@endsection
