@extends('layouts.app',['pageTitle'=>'Buat Tugas'])
@section('content')
<div class="page-head"><div><h1>Buat tugas rumah</h1><p>Tugas dibuat singkat, personal, dan tidak membebani keluarga dengan unggahan yang tidak perlu.</p></div></div>
<form class="card stack" method="post" action="{{ route('teacher.assignments.store') }}">@csrf
<div class="grid two"><div class="stack">
<label>Jenis penerima<select name="target_type" data-target-switch><option value="class">Kelas</option><option value="group">Kelompok belajar</option></select></label>
<label data-target-class>Kelas<select data-target-id-class><option value="">Pilih kelas</option>@foreach($teaching->whereNotNull('class_id') as $item)<option value="{{ $item->class_id }}">{{ $item->schoolClass?->name }}</option>@endforeach</select></label>
<label data-target-group hidden>Kelompok<select data-target-id-group><option value="">Pilih kelompok</option>@foreach($teaching->whereNotNull('learning_group_id') as $item)<option value="{{ $item->learning_group_id }}">{{ $item->learningGroup?->name }}</option>@endforeach</select></label><input type="hidden" name="target_id" data-target-id-final>
<label>Jenis tugas<select name="assignment_type"><option value="memorization">Hafalan baru</option><option value="murajaah">Murāja‘ah</option><option value="listening">Mendengarkan murattal</option><option value="reading">Membaca</option><option value="writing">Menulis ayat</option><option value="family_activity">Aktivitas keluarga</option><option value="friday_development">Pembinaan Jumat</option><option value="general">Lainnya</option></select></label>
<label>Judul tugas<input name="title" value="{{ old('title') }}" required></label><label>Target<input name="target_text" value="{{ old('target_text') }}" required placeholder="Contoh: QS. Al-Qāri‘ah ayat 1–5"></label>
<label>Surah<select name="surah_id"><option value="">Tidak dipilih</option>@foreach($surahs as $surah)<option value="{{ $surah->id }}">{{ $surah->id }}. {{ $surah->name_latin }}</option>@endforeach</select></label><div class="form-grid"><label>Ayat awal<input type="number" name="start_verse" min="1"></label><label>Ayat akhir<input type="number" name="end_verse" min="1"></label></div>
</div><div class="stack">
<label>Qari latihan<select name="quran_audio_source_id"><option value="">Tidak memakai audio</option>@foreach($audioSources as $source)<option value="{{ $source->id }}">{{ $source->is_default ? '⭐ ' : '' }}{{ $source->reciter_name }}</option>@endforeach</select></label><div class="form-grid"><label>Pengulangan<select name="repeat_count"><option value="">Bebas</option><option>1</option><option>3</option><option>5</option><option selected>10</option><option>20</option></select></label><label>Pola ulang<select name="repeat_mode"><option value="each_ayah">Setiap ayat</option><option value="whole_selection">Seluruh pilihan</option></select></label></div>
<label>Metode<select name="learning_method"><option value="listening">Mendengar dan menirukan</option><option value="repetition">Membaca berulang</option><option value="writing">Menulis ayat</option><option value="word_arrangement">Menyusun potongan kata</option><option value="movement">Menghafal sambil bergerak</option><option value="drawing">Menggambar/visualisasi</option><option value="storytelling">Bercerita</option><option value="teach_back">Mengajarkan kembali</option><option value="custom">Metode lain</option></select></label>
<label>Instruksi<textarea name="instructions" required placeholder="Contoh: dengarkan Al-Husary 10× per ayat, lalu baca bersama orang tua.">{{ old('instructions') }}</textarea></label>
<fieldset><legend>Jenis bukti</legend><div class="checks-grid"><label class="check"><input type="checkbox" name="evidence_types[]" value="video"> Video</label><label class="check"><input type="checkbox" name="evidence_types[]" value="audio"> Audio</label><label class="check"><input type="checkbox" name="evidence_types[]" value="photo"> Foto</label><label class="check"><input type="checkbox" name="evidence_types[]" value="text"> Teks</label><label class="check"><input type="checkbox" name="evidence_types[]" value="guardian_checklist" checked> Checklist wali</label><label class="check"><input type="checkbox" name="evidence_types[]" value="none"> Tanpa unggahan</label></div></fieldset>
<label>Tenggat<input type="datetime-local" name="due_at"></label><input type="hidden" name="allow_resubmission" value="0"><label class="check"><input type="checkbox" name="allow_resubmission" value="1" checked> Izinkan perbaikan dan kirim ulang</label>
</div></div><div class="form-actions"><a class="button ghost" href="{{ route('teacher.assignments.index') }}">Batal</a><button class="button primary">Terbitkan Tugas</button></div></form>
@endsection
