{{-- @phase 4.2 Brand & Universal Home --}}
@extends('layouts.public')
@section('title', 'Sullamul Ḥifẓ Academy')
@section('description', 'Sullamul Hifz Academy: Parent Academy, pendidikan anak, Al-Qur’an, STIFIn secara proporsional, dan ruang belajar digital untuk guru serta keluarga.')
@section('content')
<section class="page-hero academy-hero"><div class="public-container page-hero-inner"><span class="public-eyebrow">SULLAMUL ḤIFẒ ACADEMY</span><h1>Belajar bersama agar pendampingan tidak terputus.</h1><p>Academy menjadi jembatan materi untuk personal, ustadz, orang tua, pengelola lembaga, dan pembelajar Al-Qur’an sesuai program yang diikuti.</p><div class="hero-actions"><a class="public-button primary" href="{{ config('sullam.academy_portal_url') }}">Masuk ke Academy</a><a class="public-button secondary" href="{{ route('public.features') }}">Lihat seluruh fitur</a></div></div></section>
<section class="public-section"><div class="public-container section-heading centered"><span class="public-eyebrow">E-COURSE</span><h2>Materi berkembang mengikuti kebutuhan pembinaan.</h2><p>Program dapat ditambah tanpa mengubah filosofi utama: Human Before Data, No Ranking Culture, dan pembinaan yang tetap berlangsung di dunia nyata.</p></div><div class="public-container academy-grid"><article><h3>Parent Academy</h3><p>Rumah dekat dengan Al-Qur’an, tahfizh tanpa tekanan, murāja‘ah, komunikasi, adab, dan istiqamah.</p></article><article><h3>STIFIn & Parenting</h3><p>STIFIn ditempatkan sebagai informasi tambahan dan hipotesis pendampingan, bukan label atau penentu kemampuan anak.</p></article><article><h3>Hidup bersama Al-Qur’an</h3><p>Menghubungkan bacaan, hafalan, murāja‘ah, pemahaman, pengamalan, serta Audio Qur’an dalam satu perjalanan.</p></article><article><h3>Pendidikan Anak</h3><p>Keteladanan, komunikasi positif, keberanian, kreativitas, karakter, dan pembelajaran melalui pengalaman.</p></article></div></section>
<section class="public-section roadmap-section"><div class="public-container two-column"><div><span class="public-eyebrow">SATU EKOSISTEM</span><h2>Academy, aplikasi TPA, dan Audio Qur’an saling terhubung.</h2><p>Satu akun dapat digunakan untuk mengikuti program, menyimpan progres, menerima rekomendasi guru, membaca materi, dan kembali ke aplikasi operasional ketika dibutuhkan.</p></div><ol class="roadmap-list"><li><strong>1. Arahan guru</strong><span>Target atau kebutuhan anak dicatat secara singkat.</span></li><li><strong>2. Academy</strong><span>Keluarga memilih e-course, artikel, video, atau aktivitas yang relevan.</span></li><li><strong>3. Audio Al-Qur’an</strong><span>Murattal dan pola pengulangan membantu latihan sesuai target.</span></li><li><strong>4. Tindak lanjut</strong><span>Orang tua dan guru berkomunikasi melalui Buku Penghubung.</span></li></ol></div></section>
@endsection
