{{-- @phase 4.2 Brand & Universal Home --}}
@extends('layouts.public')
@section('title', 'Jalur Sullamul Ḥifẓ')
@section('description', 'Jalur Sullamul Hifz untuk personal, bimbingan ustadz, keluarga, dan lembaga.')
@section('content')
<section class="page-hero"><div class="public-container page-hero-inner"><span class="public-eyebrow">JALUR PENGGUNAAN</span><h1>Satu filosofi, ruang yang mengikuti kebutuhan Anda.</h1><p>Mulai sendiri, bersama ustadz, bersama keluarga, atau melalui lembaga. Jalur dapat bertambah tanpa mencampur data privat antar-ruang.</p></div></section>
<section class="public-section"><div class="public-container program-stack">
<article class="program-row"><div class="program-index">01</div><div><span class="status-badge active">Aktif</span><h2>Personal Mandiri</h2><p>Ruang privat untuk target, jurnal, check-in, latihan, Qur’an Journey, dan program modular.</p><a class="text-link" href="{{ route('public.solution','personal') }}">Lihat solusi Personal →</a></div><div class="program-points"><span>Privat</span><span>Modular</span><span>Dapat berkembang</span></div></article>
<article class="program-row"><div class="program-index">02</div><div><span class="status-badge active">Fondasi tersedia</span><h2>Bimbingan Ustadz</h2><p>Relasi personal–ustadz berbasis persetujuan untuk setoran, koreksi, target bersama, dan evaluasi privat.</p><a class="text-link" href="{{ route('public.solution','ustadz') }}">Lihat alur bimbingan →</a></div><div class="program-points"><span>Consent</span><span>Setoran & review</span><span>Riwayat terjaga</span></div></article>
<article class="program-row" id="keluarga"><div class="program-index">03</div><div><span class="status-badge">Bertumbuh</span><h2>Keluarga</h2><p>Pendampingan orang tua–anak, baik mandiri maupun melalui lembaga, dengan batas akses sesuai usia dan persetujuan.</p><a class="text-link" href="{{ route('public.solution','keluarga') }}">Lihat solusi Keluarga →</a></div><div class="program-points"><span>Rutinitas rumah</span><span>Laporan</span><span>Privasi sehat</span></div></article>
<article class="program-row"><div class="program-index">04</div><div><span class="status-badge active">Multi-tenant</span><h2>Lembaga</h2><p>TPA, rumah tahfiz, pesantren, SD, SMP, SMA, kampus, dan komunitas dapat memakai struktur serta istilah masing-masing.</p><a class="text-link" href="{{ route('public.solution','lembaga') }}">Lihat solusi Lembaga →</a></div><div class="program-points"><span>Akademik</span><span>Komunikasi</span><span>Branding adaptif</span></div></article>
<article class="program-row"><div class="program-index">05</div><div><span class="status-badge active">Terintegrasi</span><h2>Academy</h2><p>Materi, modul, kuis, worksheet, dan sertifikat yang dapat dipakai lintas jalur sesuai hak akses.</p><a class="text-link" href="{{ route('public.academy') }}">Lihat Academy →</a></div><div class="program-points"><span>Video & modul</span><span>Kuis & tugas</span><span>Progress & sertifikat</span></div></article>
</div></section>
@endsection
