@extends('layouts.app',['pageTitle'=>auth()->user()->hasRole('head') ? 'Beranda Kepala TPA' : 'Beranda Admin'])
@section('content')
<div class="hero brand-hero"><div><span class="eyebrow">TPA AL-INSYIRAH</span><h1>Selamat datang, {{ auth()->user()->name }}</h1><p>Pantau operasional, pembelajaran, komunikasi, dan layanan publik dari satu tempat.</p></div>@if(auth()->user()->hasAnyRole(['superadmin','institution_admin']))<a class="button primary" href="{{ route('admin.students.create') }}"><x-icon name="plus" size="18"/> Tambah Santri</a>@endif</div>
<div class="stats-grid"><div class="stat-card branded-stat"><span class="stat-icon"><x-icon name="student" size="24"/></span><div><span>Santri aktif</span><strong>{{ $studentCount }}</strong></div></div><div class="stat-card branded-stat"><span class="stat-icon"><x-icon name="teacher" size="24"/></span><div><span>Guru / wali</span><strong>{{ $teacherCount }} / {{ $guardianCount }}</strong></div></div><div class="stat-card branded-stat"><span class="stat-icon"><x-icon name="academic" size="24"/></span><div><span>Kelas / kelompok</span><strong>{{ $classCount }} / {{ $groupCount }}</strong></div></div><div class="stat-card branded-stat"><span class="stat-icon"><x-icon name="calendar" size="24"/></span><div><span>Pertemuan hari ini</span><strong>{{ $todayMeetings }}</strong></div></div></div>
<div class="stats-grid three"><div class="stat-card"><span>Absensi tercatat hari ini</span><strong>{{ $todayAttendance }}</strong></div><div class="stat-card"><span>Buku penghubung aktif</span><strong>{{ $openThreads }}</strong></div><div class="stat-card"><span>Pendaftaran baru</span><strong>{{ $newRegistrations }}</strong></div></div>
@if($v610Enabled)
<section class="card"><div class="section-head"><div><h2>Perlu ditangani</h2><p class="hint">Antrean operasional yang membutuhkan keputusan.</p></div><span class="v610-status {{ ($pendingInfaq+$pendingRealisations)>0?'is-warning':'is-success' }}">{{ $pendingInfaq+$pendingRealisations }} pekerjaan</span></div><div class="v610-worklist"><a class="v610-workitem" href="{{ route('admin.infaq.index') }}"><div><h3>Pencocokan penerimaan infak</h3><small>{{ $pendingInfaq }} transaksi menunggu verifikasi mutasi</small></div><span>→</span></a><a class="v610-workitem" href="{{ route('admin.infaq.realisations.index') }}"><div><h3>Persetujuan realisasi dana</h3><small>{{ $pendingRealisations }} catatan menunggu pemeriksaan Penanggung Jawab</small></div><span>→</span></a><div class="v610-workitem"><div><h3>Kesiapan pemulihan data</h3><small>{{ $lastBackupAt ? 'Backup terakhir '.\Illuminate\Support\Carbon::parse($lastBackupAt)->diffForHumans() : 'Belum ada backup berhasil yang tercatat' }}</small></div><span class="v610-status {{ $lastBackupAt?'is-success':'is-danger' }}">{{ $lastBackupAt?'Tercatat':'Perlu tindakan' }}</span></div></div></section>
@endif
<div class="grid two"><section class="card"><div class="section-head"><h2>Akses cepat</h2></div><div class="quick-grid branded-quick-grid">@if(auth()->user()->hasAnyRole(['superadmin','institution_admin']))<a href="{{ route('admin.students.index') }}"><x-icon name="student" size="22"/><span>Data Santri</span></a><a href="{{ route('admin.guardians.index') }}"><x-icon name="profile" size="22"/><span>Data Wali</span></a><a href="{{ route('admin.academic.index') }}"><x-icon name="academic" size="22"/><span>Kelas & Jadwal</span></a><a href="{{ route('admin.imports.index') }}"><x-icon name="assignment" size="22"/><span>Impor Data</span></a><a href="{{ route('admin.ecosystem.index') }}"><x-icon name="continuity" size="22"/><span>Kendali Ekosistem</span></a>@endif
@if(auth()->user()->hasAnyPermission(['announcements.manage','friday.manage']))<a href="{{ route('admin.content.index') }}"><x-icon name="guidance" size="22"/><span>Konten</span></a>@endif
@if(auth()->user()->hasPermission('report_cards.manage') && \App\Support\Feature::enabled('report_cards', auth()->user()->institution_id, true))<a href="{{ route('admin.report-cards.index') }}"><x-icon name="report" size="22"/><span>Rapor</span></a>@endif
@if(auth()->user()->hasPermission('website.manage') && \App\Support\Feature::enabled('public_website', auth()->user()->institution_id, true))<a href="{{ route('admin.website.index') }}"><x-icon name="community" size="22"/><span>Website</span></a>@endif
@if(auth()->user()->hasPermission('reports.view'))<a href="{{ route('admin.reports.index') }}"><x-icon name="report" size="22"/><span>Ekspor</span></a>@endif
@if($v610Enabled)<a href="{{ route('admin.infaq.realisations.index') }}"><x-icon name="achievement" size="22"/><span>Infak & Dampak</span></a>@endif
</div></section><section class="card"><div class="section-head"><h2>Pengumuman terbaru</h2>@if(auth()->user()->hasPermission('announcements.manage'))<a href="{{ route('admin.content.index') }}">Kelola</a>@else<a href="{{ route('feed.announcements') }}">Lihat</a>@endif</div>@if($recentAnnouncements->isEmpty())<p class="empty">Belum ada pengumuman.</p>@else<ul class="clean-list">@foreach($recentAnnouncements as $item)<li><strong>{{ $item->title }}</strong><small>{{ optional($item->publish_at)->format('d M Y H:i') }}</small></li>@endforeach</ul>@endif</section></div>
@endsection
