@extends('layouts.app',['pageTitle'=>'Beranda Guru'])
@section('content')
<div class="hero"><div><span class="eyebrow">GURU</span><h1>Assalamu‘alaikum, {{ $teacher->nickname ?: $teacher->full_name }}</h1><p>{{ now()->translatedFormat('l, d F Y') }} · Selesaikan satu alur pertemuan sebelum membuka yang berikutnya.</p></div><a class="button primary" href="{{ route('teacher.daily.index') }}">Operasional Hari Ini</a></div>
<div class="stats-grid four"><div class="stat-card"><span>Penugasan aktif</span><strong>{{ $teachingAssignments->count() }}</strong></div><div class="stat-card"><span>Target aktif</span><strong>{{ $activeTargets }}</strong></div><div class="stat-card"><span>Bukti menunggu</span><strong>{{ $pendingSubmissions }}</strong></div><div class="stat-card"><span>Percakapan aktif</span><strong>{{ $activeThreads }}</strong></div></div>
<div class="grid two">
<section class="card"><div class="section-head"><h2>Pertemuan hari ini</h2><a href="{{ route('teacher.daily.index') }}">Kelola</a></div>@forelse($todayMeetings as $meeting)@php($target=$meeting->schoolClass ?: $meeting->learningGroup)<a class="list-row" href="{{ route('teacher.meetings.show',$meeting) }}"><div><strong>{{ $target?->name }}</strong><small>{{ $meeting->topic ?: 'Materi belum ditulis' }} · {{ $meeting->attendanceRecords->count() }} absensi · {{ $meeting->status==='completed'?'Selesai':'Berlangsung' }}</small></div><span>→</span></a>@empty<p class="empty">Belum ada pertemuan hari ini.</p>@endforelse</section>
<section class="card"><div class="section-head"><h2>Perlu diselesaikan</h2><span class="badge">{{ $openMeetings->count() }}</span></div>@forelse($openMeetings as $meeting)@php($target=$meeting->schoolClass ?: $meeting->learningGroup)<a class="list-row" href="{{ route('teacher.meetings.show',$meeting) }}"><div><strong>{{ $target?->name }}</strong><small>{{ $meeting->meeting_date->format('d M Y') }} · {{ $meeting->topic ?: 'Tanpa materi' }}</small></div><span>→</span></a>@empty<p class="empty">Semua pertemuan sudah ditutup.</p>@endforelse</section>
</div>
<section class="card"><div class="section-head"><h2>Kelas dan kelompok</h2><a href="{{ route('teacher.assignments.create') }}">+ Buat tugas</a></div><div class="cards-list">@forelse($teachingAssignments as $item)@php($target=$item->schoolClass ?: $item->learningGroup)<a class="item-card" href="{{ $item->class_id ? route('teacher.classrooms.class',$item->class_id) : route('teacher.classrooms.group',$item->learning_group_id) }}"><div><strong>{{ $target?->name }}</strong><small>{{ $item->program?->name }}</small></div><span>→</span></a>@empty<p class="empty">Belum ada penugasan aktif. Hubungi admin lembaga.</p>@endforelse</div></section>
@endsection
