@extends('layouts.app',['pageTitle'=>'Akademik'])
@section('content')
<div class="page-head"><div><h1>Akademik</h1><p>{{ $year?->name ?? 'Belum ada tahun ajaran aktif' }} · kelas utama dan kelompok belajar dikelola terpisah.</p></div></div>
<div class="grid three">
<section class="card"><h2>Tahun ajaran</h2><p class="hint">Buat tahun baru tanpa menghapus riwayat tahun sebelumnya.</p><form class="stack compact" method="post" action="{{ route('admin.academic.years.store') }}">@csrf<label>Nama<input name="name" placeholder="2027/2028" required></label><div class="form-grid"><label>Mulai<input type="date" name="start_date" required></label><label>Selesai<input type="date" name="end_date" required></label></div><label class="check"><input type="checkbox" name="is_active" value="1"> Jadikan tahun aktif</label><button class="button secondary">Tambah tahun</button></form></section>
<section class="card"><h2>Jenjang</h2><form class="stack compact" method="post" action="{{ route('admin.academic.levels.store') }}">@csrf<label>Nama<input name="name" required></label><label>Kode<input name="code" required></label><label>Urutan<input type="number" name="sequence" min="0"></label><label>Deskripsi<textarea name="description"></textarea></label><button class="button secondary">Tambah jenjang</button></form></section>
<section class="card"><h2>Program</h2><form class="stack compact" method="post" action="{{ route('admin.academic.programs.store') }}">@csrf<label>Nama<input name="name" required></label><label>Kode<input name="code" required></label><label>Kategori<select name="category"><option value="quran">Al-Qur’an</option><option value="character">Pembinaan</option><option value="talent">Bakat</option><option value="parenting">Parenting</option><option value="community">Community</option></select></label><label>Deskripsi<textarea name="description"></textarea></label><button class="button secondary">Tambah program</button></form></section>
</div>
<div class="grid two">
<section class="card"><div class="section-head"><h2>Kelas utama</h2><span>{{ $classes->count() }} kelas</span></div><div class="cards-list">@foreach($classes as $class)<div class="item-card static"><div><strong>{{ $class->name }}</strong><small>{{ $class->level->name }} · {{ $class->activeEnrollments->count() }}/{{ $class->capacity ?: '∞' }} santri</small></div></div>@endforeach</div><details><summary>+ Tambah kelas</summary><form class="stack compact" method="post" action="{{ route('admin.academic.classes.store') }}">@csrf<input type="hidden" name="academic_year_id" value="{{ $year?->id }}"><label>Jenjang<select name="level_id" required>@foreach($levels as $level)<option value="{{ $level->id }}">{{ $level->name }}</option>@endforeach</select></label><label>Nama kelas<input name="name" required></label><label>Kode<input name="code" required placeholder="MUSTAWA-AWAL-C"></label><label>Kapasitas<input type="number" name="capacity" min="1"></label><button class="button primary">Simpan kelas</button></form></details></section>
<section class="card"><div class="section-head"><h2>Kelompok belajar</h2><span>{{ $groups->count() }} kelompok</span></div><div class="cards-list">@foreach($groups as $group)<a class="item-card" href="{{ route('admin.academic.groups.show',$group) }}"><div><strong>{{ $group->name }}</strong><small>{{ $group->program->name }} · {{ $group->activeMemberships->count() }} santri</small></div><span>→</span></a>@endforeach</div><details><summary>+ Tambah kelompok</summary><form class="stack compact" method="post" action="{{ route('admin.academic.groups.store') }}">@csrf<input type="hidden" name="academic_year_id" value="{{ $year?->id }}"><label>Program<select name="program_id" required>@foreach($programs as $program)<option value="{{ $program->id }}">{{ $program->name }}</option>@endforeach</select></label><label>Nama kelompok<input name="name" required></label><label>Kode<input name="code" required placeholder="TAHFIZH-C"></label><label>Kapasitas<input type="number" name="capacity" min="1"></label><button class="button primary">Simpan kelompok</button></form></details></section>
</div>
<div class="grid two">
<section class="card"><div class="section-head"><h2>Penugasan guru</h2><span>{{ $assignments->count() }} aktif</span></div>@foreach($assignments as $item)<div class="list-row"><div><strong>{{ $item->teacher->full_name }}</strong><small>{{ ($item->schoolClass ?: $item->learningGroup)?->name }} · {{ $item->program->name }}</small></div></div>@endforeach<details><summary>+ Tambah penugasan</summary><form class="stack compact" method="post" action="{{ route('admin.academic.teacher-assignments.store') }}">@csrf<input type="hidden" name="academic_year_id" value="{{ $year?->id }}"><label>Guru<select name="teacher_id" required>@foreach($teachers as $teacher)<option value="{{ $teacher->id }}">{{ $teacher->full_name }}</option>@endforeach</select></label><label>Program<select name="program_id" required>@foreach($programs as $program)<option value="{{ $program->id }}">{{ $program->name }}</option>@endforeach</select></label><label>Jenis target<select name="target_type" data-target-switch><option value="class">Kelas</option><option value="group">Kelompok</option></select></label><label data-target-class>Kelas<select name="class_id"><option value="">Pilih</option>@foreach($classes as $class)<option value="{{ $class->id }}">{{ $class->name }}</option>@endforeach</select></label><label data-target-group hidden>Kelompok<select name="learning_group_id"><option value="">Pilih</option>@foreach($groups as $group)<option value="{{ $group->id }}">{{ $group->name }}</option>@endforeach</select></label><label>Mulai<input type="date" name="valid_from" value="{{ now()->format('Y-m-d') }}"></label><label>Selesai<input type="date" name="valid_until"></label><button class="button primary">Simpan penugasan</button></form></details></section>
<section class="card"><div class="section-head"><h2>Jadwal</h2><span>{{ $schedules->count() }} aktif</span></div>@php($days=[1=>'Senin',2=>'Selasa',3=>'Rabu',4=>'Kamis',5=>'Jumat',6=>'Sabtu',7=>'Ahad'])@foreach($schedules as $schedule)<div class="list-row"><div><strong>{{ ($schedule->schoolClass ?: $schedule->learningGroup)?->name }}</strong><small>{{ $days[$schedule->day_of_week] }} · {{ substr($schedule->start_time,0,5) }}–{{ substr($schedule->end_time,0,5) }} · {{ $schedule->teacherAssignment?->teacher?->full_name }}</small></div></div>@endforeach<details><summary>+ Tambah jadwal</summary><form class="stack compact" method="post" action="{{ route('admin.academic.schedules.store') }}">@csrf<input type="hidden" name="academic_year_id" value="{{ $year?->id }}"><label>Penugasan guru<select name="teacher_assignment_id" required>@foreach($assignments as $item)<option value="{{ $item->id }}">{{ $item->teacher->full_name }} — {{ ($item->schoolClass ?: $item->learningGroup)?->name }} — {{ $item->program->name }}</option>@endforeach</select></label><label>Hari<select name="day_of_week">@foreach($days as $id=>$day)<option value="{{ $id }}">{{ $day }}</option>@endforeach</select></label><div class="form-grid"><label>Mulai<input type="time" name="start_time" required></label><label>Selesai<input type="time" name="end_time" required></label></div><label>Lokasi<input name="location"></label><button class="button primary">Simpan jadwal</button></form></details></section>
</div>
@endsection
