@extends('layouts.app',['pageTitle'=>'Kendali Ekosistem'])
@section('content')
<div class="page-head"><div><span class="eyebrow">V4.0 · SATU KENDALI</span><h1>Kendali Ekosistem</h1><p>Tetapkan akses Personal, moderasi community, dan rekonsiliasi pembayaran tanpa redeploy.</p></div></div>

<section class="card" style="margin-bottom:18px"><div class="section-head"><div><span class="eyebrow">AKSES PERSONAL</span><h2>Program yang didaftarkan per akun</h2><p class="muted">Yang tidak dicentang tidak muncul dan tidak dapat dibuka oleh akun tersebut. Histori lama tetap tersimpan.</p></div><span class="badge">{{ $personalUsers->count() }} akun</span></div>
<div class="v4-admin-access-list">@forelse($personalUsers as $personalUser)
@php
    $activeKeys = collect($personalAccessMaps[$personalUser->id] ?? [])->filter()->keys()->all();
@endphp
<form method="post" action="{{ route('admin.ecosystem.personal.access',$personalUser) }}" class="v4-admin-access">@csrf @method('put')
    <div><strong>{{ $personalUser->name }}</strong><small>{{ $personalUser->email }}</small></div>
    <div class="v4-access-options">@foreach($moduleDefinitions as $key=>$definition)<label><input type="checkbox" name="programs[]" value="{{ $key }}" @checked(in_array($key,$activeKeys,true))><span>{{ $definition['title'] }}</span></label>@endforeach</div>
    <button class="button secondary small" type="submit">Simpan akses</button>
</form>@empty<p class="muted">Belum ada akun Personal.</p>@endforelse</div></section>

<div class="grid two">
<section class="card"><div class="section-head"><div><span class="eyebrow">RUANG COMMUNITY</span><h2>Kebijakan sebelum aktivasi</h2><p class="muted">Semua ruang memakai approval manusia; media anak ditolak secara default.</p></div></div><form method="post" action="{{ route('admin.ecosystem.community-spaces.store') }}" class="stack">@csrf<label>Nama ruang<input name="name" maxlength="160" required></label><label>Deskripsi<textarea name="description" rows="3" maxlength="1000"></textarea></label><button class="button secondary" type="submit">Buat sebagai draft</button></form><div class="stack" style="margin-top:16px">@foreach($communitySpaces as $space)<form method="post" action="{{ route('admin.ecosystem.community-spaces.update',$space) }}" class="list-row">@csrf @method('put')<div><strong>{{ $space->name }}</strong><small>{{ $space->description }}</small></div><select name="status" onchange="this.form.submit()"><option value="draft" @selected($space->status==='draft')>Draft</option><option value="active" @selected($space->status==='active')>Aktif</option><option value="archived" @selected($space->status==='archived')>Arsip</option></select></form>@endforeach</div></section>
<section class="card"><div class="section-head"><div><span class="eyebrow">MODERASI MANUSIA</span><h2>Community menunggu review</h2></div><span class="badge">{{ $pendingPosts->count() }}</span></div><div class="stack">@forelse($pendingPosts as $post)<article class="v4-admin-review"><small>{{ $post->space?->name }} · {{ $post->creator?->name }}</small><p>{{ $post->body }}</p><form method="post" action="{{ route('admin.ecosystem.community.moderate',$post) }}">@csrf @method('put')<textarea name="reason" rows="2" maxlength="1000" placeholder="Catatan keputusan (opsional)"></textarea><div><button class="button primary small" name="action" value="approve">Terbitkan</button><button class="button danger small" name="action" value="reject">Tolak</button></div></form></article>@empty<p class="muted">Tidak ada tulisan yang menunggu.</p>@endforelse</div></section>
<section class="card"><div class="section-head"><div><span class="eyebrow">REKONSILIASI BSI</span><h2>Pembayaran menunggu</h2><p class="muted">{{ $destination['bank_name'] }} · {{ $destination['account_number'] }}</p></div><span class="badge">{{ $pendingPayments->count() }}</span></div><div class="stack">@forelse($pendingPayments as $payment)<article class="v4-admin-review"><small>{{ $payment->user?->name }} · {{ $payment->created_at->translatedFormat('d M Y H:i') }}</small><strong>Rp{{ number_format((float)$payment->amount,0,',','.') }}</strong><p>{{ str($payment->purpose)->replace('_',' ')->headline() }} · Pengirim: {{ data_get($payment->metadata,'sender_name','—') }}</p><form method="post" action="{{ route('admin.ecosystem.payments.update',$payment) }}">@csrf @method('put')<textarea name="reason" rows="2" maxlength="1000" placeholder="Alasan wajib bila ditolak"></textarea><div><button class="button primary small" name="decision" value="paid">Tandai terverifikasi</button><button class="button danger small" name="decision" value="rejected">Tolak</button></div></form></article>@empty<p class="muted">Tidak ada pembayaran yang menunggu.</p>@endforelse</div></section>
</div>
@endsection
