@extends('layouts.app',['pageTitle'=>'Profil Santri'])
@section('content')
<div class="page-head"><div><span class="eyebrow">{{ $student->student_code }}</span><h1>{{ $student->full_name }}</h1><p>{{ $student->currentEnrollment?->schoolClass?->name ?? 'Belum ditempatkan' }}</p></div><div class="actions"><a class="button secondary" href="{{ route('admin.academic-core.index') }}">Academic Core</a><a class="button secondary" href="{{ route('admin.students.edit',$student) }}">Edit data</a></div></div>
<div class="grid three">
<section class="card"><h2>Identitas</h2><dl class="details"><dt>Nama panggilan</dt><dd>{{ $student->nickname ?: '—' }}</dd><dt>Tanggal lahir</dt><dd>{{ $student->birth_date?->format('d M Y') ?: '—' }}</dd><dt>Status</dt><dd>{{ $student->status }}</dd><dt>STIFIn</dt><dd>{{ $student->stifin_status==='tested'?($student->stifin_result?:'Sudah dites'):'Belum Dites' }}</dd></dl></section>
<section class="card"><h2>Wali terhubung</h2>@forelse($student->guardians as $guardian)<div class="list-row"><div><strong>{{ $guardian->full_name }}</strong><small>{{ $guardian->pivot->relationship }} · {{ $guardian->phone }}</small>@if($guardian->user)<div class="inline-actions"><form method="post" action="{{ route('admin.accounts.invitation',$guardian->user) }}">@csrf<button class="button ghost small" type="submit">Buat tautan aktivasi</button></form></div><details><summary>Atur ulang kata sandi manual</summary><form class="stack compact" method="post" action="{{ route('admin.accounts.password',$guardian->user) }}">@csrf @method('PUT')<label>Sandi baru<input type="password" name="password" minlength="12" required></label><label>Konfirmasi<input type="password" name="password_confirmation" minlength="12" required></label><button class="button secondary">Simpan</button></form></details>@endif</div></div>@empty<p class="empty">Belum ada wali.</p>@endforelse<details><summary>+ Hubungkan wali lain</summary><form method="post" action="{{ route('admin.students.guardians.store',$student) }}" class="stack compact">@csrf<label>Nama wali<input name="guardian_name" required></label><label>Hubungan<select name="guardian_relationship"><option value="mother">Ibu</option><option value="father">Ayah</option><option value="guardian">Wali</option><option value="grandparent">Kakek/Nenek</option></select></label><label>Nomor telepon<input name="guardian_phone" required></label><label>Email<input type="email" name="guardian_email"></label><label>Kata sandi awal<input type="password" name="guardian_password" minlength="12" placeholder="Opsional; kosongkan untuk aktivasi melalui tautan aman"></label><button class="button secondary">Hubungkan Wali</button></form></details></section>
<section class="card"><h2>Ringkasan catatan</h2><dl class="details"><dt>Target hafalan</dt><dd>{{ $student->memorizationTargets->count() }} target</dd><dt>Tahsīn</dt><dd>{{ $student->tahsinRecords->count() }} catatan</dd><dt>Setoran</dt><dd>{{ $student->memorizationRecords->count() }} catatan</dd><dt>Murāja‘ah</dt><dd>{{ $student->murajaahRecords->count() }} catatan</dd><dt>Observasi belajar</dt><dd>{{ $student->learningObservations->count() }} catatan</dd></dl></section>
</div>
<div class="grid two">
<section class="card"><h2>Target hafalan</h2>@forelse($student->memorizationTargets->sortByDesc('created_at')->take(15) as $target)<div class="list-row"><div><strong>{{ $target->surah?->name_latin }} {{ $target->start_verse }}–{{ $target->end_verse }}</strong><small>{{ $target->rubu?->name ?? 'Rubu belum dipilih' }} · {{ $target->marhalah?->name ?? 'Marhalah belum dipilih' }} · {{ str_replace('_',' ',$target->status) }}</small><p>{{ $target->notes }}</p></div></div>@empty<p class="empty">Belum ada target.</p>@endforelse</section>
<section class="card"><h2>Observasi metode belajar</h2>@forelse($student->learningObservations->sortByDesc('observed_at')->take(15) as $item)<div class="list-row"><div><strong>{{ $item->method_name }}</strong><small>{{ str_replace('_',' ',$item->category) }} · {{ str_replace('_',' ',$item->effectiveness ?? 'needs_more_observation') }} · {{ $item->teacher?->full_name }}</small><p>{{ $item->response }} {{ $item->notes }}</p></div></div>@empty<p class="empty">Belum ada observasi.</p>@endforelse</section>
<section class="card"><h2>Setoran terbaru</h2>@forelse($student->memorizationRecords->take(10) as $record)<div class="list-row"><div><strong>{{ $record->surah?->name_latin }} {{ $record->start_verse }}–{{ $record->end_verse }}</strong><small>{{ $record->recorded_at?->format('d M Y') }} · {{ str_replace('_',' ',$record->result) }}</small></div></div>@empty<p class="empty">Belum ada catatan.</p>@endforelse</section>
<section class="card"><h2>Murāja‘ah terbaru</h2>@forelse($student->murajaahRecords->take(10) as $record)<div class="list-row"><div><strong>{{ $record->surah?->name_latin }} {{ $record->start_verse }}–{{ $record->end_verse }}</strong><small>{{ $record->recorded_at?->format('d M Y') }} · {{ str_replace('_',' ',$record->result) }}</small></div></div>@empty<p class="empty">Belum ada catatan.</p>@endforelse</section>
</div>
@endsection
