@extends('layouts.app',['pageTitle'=>'Pustaka Qur’an'])
@section('content')
<div class="page-head"><div><span class="eyebrow">V1.6.1 QARI TAHFIZH</span><h1>Pustaka Audio & Video</h1><p>Kelola dua qari utama untuk tahfizh, timing ayat, halaman Mushaf, preset pengulangan, dan video terkurasi.</p></div><a class="button secondary" href="{{ route('quran-practice.index') }}">Buka pemutar</a></div>
<div class="stats-grid four"><div class="stat-card"><span>Qari siap</span><strong>{{ $qariReadyCount }}/{{ $expectedQariCount }}</strong></div><div class="stat-card"><span>Total timing</span><strong>{{ $timingCount }}/{{ $expectedTimingCount }}</strong></div><div class="stat-card"><span>Audio utama</span><strong>{{ $defaultTimingCount }}/564</strong></div><div class="stat-card"><span>Preset aktif</span><strong>{{ $presetCount }}</strong></div></div>
<section class="card quran-sync-card"><div><h2>Kelengkapan dua qari Juz 30</h2><p>{{ $qariReadyCount >= $expectedQariCount ? 'Al-Husary dan Al-Minshawi sudah lengkap. Pengguna dapat memilih qari untuk ayat, rentang, surah, halaman, dan rubu’.' : 'Jalankan sinkronisasi sampai kedua qari mencapai masing-masing 564 timing ayat.' }}</p><div class="quran-completion"><span style="width:{{ min(100,round(($timingCount/max(1,$expectedTimingCount))*100)) }}%"></span></div><small>{{ min(100,round(($timingCount/max(1,$expectedTimingCount))*100)) }}% lengkap · {{ $surahCount }}/37 surah pada sumber utama · {{ $pageCount }} halaman</small></div><form method="post" action="{{ route('admin.quran-library.sync') }}">@csrf<button class="button primary">Sinkronkan dua qari sekarang</button></form></section>
<div class="grid two">
<section class="card"><h2>Sumber audio tahfizh</h2>@forelse($sources as $source)<div class="list-row"><div><strong>{{ $source->is_default ? '⭐ ' : '' }}{{ $source->reciter_name }}</strong><small>{{ data_get($source->metadata,'learning_role',$source->is_default ? 'Qari utama' : 'Qari tambahan') }} · {{ $source->timings_count }}/564 timing</small><p>{{ data_get($source->metadata,'description') }}</p><small>{{ $source->rewaya }} · Sumber: {{ data_get($source->metadata,'source_attribution','MP3Quran.net') }}</small></div><span class="badge">{{ $source->is_default ? 'utama' : 'pilihan' }}</span></div>@empty<p class="empty">Belum ada sumber audio.</p>@endforelse</section>
<section class="card"><h2>Tambah video terkurasi</h2><p class="hint">Gunakan video yang memiliki izin tayang/sematan. Simpan sebagai draf sampai diperiksa.</p><form class="stack compact" method="post" action="{{ route('admin.quran-library.videos.store') }}">@csrf<label>Judul<input name="title" required placeholder="Contoh: Talaqqi An-Nās bersama guru"></label><div class="form-grid"><label>Jenis sumber<select name="source_type"><option value="youtube">YouTube</option><option value="direct">MP4 langsung</option></select></label><label>Status<select name="status"><option value="draft">Draf</option><option value="published">Terbit</option></select></label></div><label>URL video<input type="url" name="video_url" required placeholder="https://..."></label><label>Surah<select name="surah_id"><option value="">Umum</option>@foreach($surahs as $surah)<option value="{{ $surah->id }}">{{ $surah->id }}. {{ $surah->name_latin }}</option>@endforeach</select></label><div class="form-grid"><label>Ayat awal<input type="number" name="start_verse" min="1"></label><label>Ayat akhir<input type="number" name="end_verse" min="1"></label></div><div class="form-grid"><label>Mulai detik<input type="number" name="start_seconds" min="0"></label><label>Selesai detik<input type="number" name="end_seconds" min="1"></label></div><label>Saran jumlah ulangan<input type="number" name="default_repeat" min="1" max="100" value="1"></label><label>Catatan<textarea name="notes" rows="3" placeholder="Sumber, qari, tujuan penggunaan, dan hasil pemeriksaan"></textarea></label><button class="button primary">Simpan video</button></form></section>
</div>
<section class="card"><div class="section-head"><h2>Preset latihan</h2><span>{{ $presets->total() }} data</span></div>@forelse($presets as $preset)<div class="list-row"><div><strong>{{ $preset->title }}</strong><small>{{ $preset->mode }} · {{ $preset->repeat_count === 0 ? 'tanpa batas' : $preset->repeat_count.'×' }} · {{ $preset->repeat_scope }}</small><p>{{ $preset->description }}</p></div><span class="badge">{{ $preset->is_featured ? 'unggulan' : $preset->status }}</span></div>@empty<p class="empty">Preset akan dibuat setelah sinkronisasi.</p>@endforelse{{ $presets->links() }}</section>
<section class="card"><div class="section-head"><h2>Video tersimpan</h2><span>{{ $videos->count() }}</span></div>@forelse($videos as $video)<div class="list-row"><div><strong>{{ $video->title }}</strong><small>{{ $video->source_type }} · {{ $video->surah?->name_latin ?? 'Umum' }}</small><p>{{ $video->notes }}</p></div><form class="inline-form" method="post" action="{{ route('admin.quran-library.videos.update',$video) }}">@csrf @method('PUT')<input type="hidden" name="title" value="{{ $video->title }}"><input type="hidden" name="default_repeat" value="{{ $video->default_repeat }}"><input type="hidden" name="notes" value="{{ $video->notes }}"><select name="status"><option value="draft" @selected($video->status==='draft')>Draf</option><option value="published" @selected($video->status==='published')>Terbit</option><option value="archived" @selected($video->status==='archived')>Arsip</option></select><button class="button small secondary">Simpan</button></form></div>@empty<p class="empty">Belum ada video. Video tidak diisi otomatis agar tetap terkurasi.</p>@endforelse</section>
@endsection
