@extends('layouts.app',['pageTitle'=>'Pertemuan'])
@section('content')
@php
$targetEntity=$meeting->schoolClass ?: $meeting->learningGroup;
$statusLabels=['draft'=>'Draf','ongoing'=>'Berlangsung','completed'=>'Selesai','cancelled'=>'Dibatalkan'];
@endphp
<div class="page-head"><div><span class="eyebrow">{{ $statusLabels[$meeting->status] ?? strtoupper($meeting->status) }}</span><h1>{{ $targetEntity?->name }}</h1><p>{{ $meeting->meeting_date->format('d M Y') }} · {{ $meeting->topic ?: 'Materi belum ditulis' }}</p></div><div class="actions"><a class="button secondary" href="{{ route('teacher.meetings.attendance',$meeting) }}">Isi/Edit Absensi</a><a class="button ghost" href="{{ route('quran-practice.index') }}">Latihan Al-Qur’an</a></div></div>
<div class="stats-grid four"><div class="stat-card"><span>Absensi</span><strong>{{ $meeting->attendanceRecords->count() }}/{{ $students->count() }}</strong></div><div class="stat-card"><span>Catatan Tahsīn</span><strong>{{ $meeting->tahsinRecords->count() }}</strong></div><div class="stat-card"><span>Setoran</span><strong>{{ $meeting->memorizationRecords->count() }}</strong></div><div class="stat-card"><span>Murāja‘ah</span><strong>{{ $meeting->murajaahRecords->count() }}</strong></div></div>
<section class="card"><div class="section-head"><div><h2>Target aktif</h2><p class="hint">Pilih target saat mencatat setoran agar riwayat dan status target selalu terhubung.</p></div><a class="button small secondary" href="{{ route('teacher.learning-plan.index') }}">Kelola target</a></div>@forelse($targets as $target)<div class="list-row"><div><strong>{{ $target->student->full_name }} · {{ $target->surah->name_latin }} {{ $target->start_verse }}–{{ $target->end_verse }}</strong><small>{{ $target->rubu?->name ?? 'Rubu belum dipilih' }} · {{ $target->marhalah?->name ?? 'Marhalah belum dipilih' }}</small></div><a class="button small ghost" href="{{ route('quran-practice.target',$target) }}">▶ Latih</a></div>@empty<p class="empty">Belum ada target aktif.</p>@endforelse</section>
<div class="grid three">
<section class="card"><h2>Catat Tahsīn</h2><form class="stack compact" method="post" action="{{ route('teacher.meetings.tahsin.store',$meeting) }}">@csrf
<label>Santri<select name="student_id" required><option value="">Pilih</option>@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->full_name }}</option>@endforeach</select></label>
<label>Bagian yang dibaca<input name="material_text" required></label>
<label>Penilaian umum<select name="overall_status"><option value="good">Baik</option><option value="practice_needed">Perlu latihan</option><option value="guidance_needed">Perlu pendampingan</option><option value="special_correction">Perlu perbaikan khusus</option></select></label>
<div class="form-grid"><label>Kelancaran<select name="fluency_status"><option value="">Tidak dinilai</option><option value="strong">Kuat</option><option value="developing">Berkembang</option><option value="needs_guidance">Perlu pendampingan</option></select></label><label>Makhraj<select name="makhraj_status"><option value="">Tidak dinilai</option><option value="strong">Kuat</option><option value="developing">Berkembang</option><option value="needs_guidance">Perlu pendampingan</option></select></label><label>Tajwid<select name="tajwid_status"><option value="">Tidak dinilai</option><option value="strong">Kuat</option><option value="developing">Berkembang</option><option value="needs_guidance">Perlu pendampingan</option></select></label><label>Adab belajar<select name="adab_status"><option value="">Tidak dinilai</option><option value="consistent">Konsisten</option><option value="developing">Berkembang</option><option value="needs_guidance">Perlu pendampingan</option></select></label></div>
<label>Keputusan<select name="decision"><option value="continue">Lanjut</option><option value="repeat">Ulang</option><option value="strengthen">Penguatan</option></select></label><label>Catatan<textarea name="teacher_notes"></textarea></label><label>Tindak lanjut<input name="follow_up" placeholder="Contoh: ulang tiga kali di rumah"></label><button class="button primary">Simpan Tahsīn</button></form></section>

<section class="card"><h2>Catat Setoran Tahfizh</h2><form class="stack compact" method="post" action="{{ route('teacher.meetings.memorization.store',$meeting) }}">@csrf
<label>Santri<select name="student_id" required><option value="">Pilih</option>@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->full_name }}</option>@endforeach</select></label>
<label>Target terkait<select name="memorization_target_id"><option value="">Cari otomatis dari surat dan ayat</option>@foreach($targets as $target)<option value="{{ $target->id }}">{{ $target->student->full_name }} — {{ $target->surah->name_latin }} {{ $target->start_verse }}–{{ $target->end_verse }}</option>@endforeach</select></label>
<label>Jenis<select name="record_type"><option value="new_memorization">Hafalan baru</option><option value="initial_repetition">Pengulangan awal</option><option value="home_submission">Setoran rumah</option><option value="class_submission">Setoran kelas</option><option value="tasmi">Tasmi‘</option><option value="exam">Ujian</option></select></label>
<label>Marhalah<select name="marhalah_type_id"><option value="">Tidak dipilih</option>@foreach($marhalah as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select></label><label>Surah<select name="surah_id" required>@foreach($surahs as $surah)<option value="{{ $surah->id }}">{{ $surah->id }}. {{ $surah->name_latin }}</option>@endforeach</select></label><div class="form-grid"><label>Ayat awal<input type="number" name="start_verse" min="1" required></label><label>Ayat akhir<input type="number" name="end_verse" min="1" required></label></div>
<label>Hasil<select name="result"><option value="fluent">Lulus/lancar</option><option value="fair">Lulus dengan penguatan</option><option value="repeat_needed">Perlu diulang</option><option value="postponed">Belum dinilai</option></select></label><div class="form-grid"><label>Kelancaran<select name="fluency_status"><option value="strong">Kuat</option><option value="developing">Berkembang</option><option value="needs_repetition">Perlu pengulangan</option></select></label><label>Tajwid<select name="tajwid_status"><option value="strong">Kuat</option><option value="developing">Berkembang</option><option value="needs_correction">Perlu koreksi</option></select></label><label>Jumlah kesalahan<input type="number" min="0" name="error_count"></label><label>Bantuan<select name="assistance_level"><option value="none">Tanpa bantuan</option><option value="little">Sedikit bantuan</option><option value="several">Beberapa kali</option><option value="much">Banyak bantuan</option></select></label></div><label>Rekomendasi latihan<input name="review_recommendation" placeholder="Al-Husary 10× per ayat"></label><label>Tindak lanjut<input name="follow_up"></label><label>Catatan<textarea name="teacher_notes"></textarea></label><button class="button primary">Simpan Setoran</button></form></section>

<section class="card"><h2>Catat Murāja‘ah</h2><form class="stack compact" method="post" action="{{ route('teacher.meetings.murajaah.store',$meeting) }}">@csrf
<label>Santri<select name="student_id" required><option value="">Pilih</option>@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->full_name }}</option>@endforeach</select></label><label>Jenis<select name="murajaah_type"><option value="scheduled">Terjadwal</option><option value="random_recall">Pemanggilan acak</option><option value="continuation">Sambung ayat</option><option value="tasmi">Tasmi‘</option><option value="home">Di rumah</option></select></label><label>Surah<select name="surah_id" required>@foreach($surahs as $surah)<option value="{{ $surah->id }}">{{ $surah->id }}. {{ $surah->name_latin }}</option>@endforeach</select></label><div class="form-grid"><label>Ayat awal<input type="number" name="start_verse" min="1" required></label><label>Ayat akhir<input type="number" name="end_verse" min="1" required></label></div><label>Hasil<select name="result"><option value="maintained">Masih terjaga</option><option value="strengthening_needed">Perlu dikuatkan</option><option value="reactivation_needed">Perlu dipanggil kembali</option></select></label><label>Kekuatan hafalan<select name="strength_status"><option value="strong">Kuat</option><option value="fair">Cukup terjaga</option><option value="weak">Perlu penguatan</option><option value="recall_needed">Perlu dipanggil kembali</option></select></label><label>Bantuan<select name="assistance_level"><option value="none">Tanpa bantuan</option><option value="little">Sedikit bantuan</option><option value="several">Beberapa kali</option><option value="much">Banyak bantuan</option></select></label><label>Jadwalkan ulang<input type="date" name="next_review_date"></label><label>Rekomendasi<input name="review_recommendation" placeholder="Minshawi satu surat 3×"></label><label>Catatan<textarea name="teacher_notes"></textarea></label><button class="button primary">Simpan Murāja‘ah</button></form></section>
</div>
@if($meeting->status!=='completed')<section class="card finish-card"><div><h2>Tutup dan bagikan ringkasan</h2><p>Absensi seluruh santri wajib lengkap. Ringkasan hanya terlihat wali bila opsi publikasi dicentang.</p></div><form method="post" action="{{ route('teacher.meetings.finish',$meeting) }}">@csrf @method('PUT')<textarea name="general_notes" placeholder="Catatan internal guru"></textarea><textarea name="guardian_summary" placeholder="Ringkasan hangat untuk wali: materi, perkembangan umum, dan tindak lanjut"></textarea><label class="check"><input type="checkbox" name="publish_summary" value="1"> Tampilkan ringkasan kepada wali</label><button class="button primary">Selesaikan Pertemuan</button></form></section>@endif
@endsection
