@extends('layouts.app',['pageTitle'=>'Pertemuan'])
@section('content')
@php($target=$meeting->schoolClass ?: $meeting->learningGroup)
<div class="page-head"><div><span class="eyebrow">{{ strtoupper($meeting->status) }}</span><h1>{{ $target?->name }}</h1><p>{{ $meeting->meeting_date->format('d M Y') }} · {{ $meeting->topic ?: 'Tanpa materi umum' }}</p></div><a class="button secondary" href="{{ route('teacher.meetings.attendance',$meeting) }}">Isi/Edit Absensi</a></div>
<div class="stats-grid four"><div class="stat-card"><span>Absensi</span><strong>{{ $meeting->attendanceRecords->count() }}/{{ $students->count() }}</strong></div><div class="stat-card"><span>Catatan tahsīn</span><strong>{{ $meeting->tahsinRecords->count() }}</strong></div><div class="stat-card"><span>Setoran</span><strong>{{ $meeting->memorizationRecords->count() }}</strong></div><div class="stat-card"><span>Murāja‘ah</span><strong>{{ $meeting->murajaahRecords->count() }}</strong></div></div>
<div class="grid three">
<section class="card"><h2>Catat Tahsīn</h2><p class="hint">Tidak wajib untuk semua santri.</p><form class="stack compact" method="post" action="{{ route('teacher.meetings.tahsin.store',$meeting) }}">@csrf<label>Santri<select name="student_id" required><option value="">Pilih</option>@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->full_name }}</option>@endforeach</select></label><label>Bagian yang dibaca<input name="material_text" required></label><label>Status<select name="overall_status"><option value="good">Baik</option><option value="practice_needed">Perlu Latihan</option><option value="guidance_needed">Perlu Pendampingan</option><option value="special_correction">Perlu Perbaikan Khusus</option></select></label><label>Fokus (boleh beberapa)<select name="focus_categories[]" multiple><option value="makhraj">Makhraj</option><option value="mad">Panjang-pendek</option><option value="ghunnah">Dengung</option><option value="fluency">Kelancaran</option><option value="waqaf">Waqaf dan ibtida’</option></select></label><label>Catatan<textarea name="teacher_notes"></textarea></label><label>Tindak lanjut<input name="follow_up" placeholder="Contoh: ulang di rumah"></label><button class="button primary">Simpan Tahsīn</button></form></section>
<section class="card"><h2>Catat Setoran</h2><form class="stack compact" method="post" action="{{ route('teacher.meetings.memorization.store',$meeting) }}">@csrf<label>Santri<select name="student_id" required><option value="">Pilih</option>@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->full_name }}</option>@endforeach</select></label><label>Jenis setoran<select name="record_type"><option value="new_memorization">Hafalan Baru</option><option value="initial_repetition">Pengulangan Awal</option><option value="home_submission">Setoran Rumah</option><option value="class_submission">Setoran Kelas</option><option value="tasmi">Tasmi‘</option><option value="exam">Ujian</option></select></label><label>Marhalah<select name="marhalah_type_id"><option value="">Tidak dipilih</option>@foreach($marhalah as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select></label><label>Surah<select name="surah_id" required>@foreach($surahs as $surah)<option value="{{ $surah->id }}">{{ $surah->id }}. {{ $surah->name_latin }}</option>@endforeach</select></label><div class="form-grid"><label>Ayat awal<input type="number" name="start_verse" min="1" required></label><label>Ayat akhir<input type="number" name="end_verse" min="1" required></label></div><label>Hasil<select name="result"><option value="fluent">Lancar</option><option value="fair">Cukup Lancar</option><option value="repeat_needed">Perlu Pengulangan</option><option value="postponed">Ditunda</option></select></label><label>Bantuan<select name="assistance_level"><option value="none">Tanpa Bantuan</option><option value="little">Sedikit Bantuan</option><option value="several">Beberapa Kali Bantuan</option><option value="much">Banyak Bantuan</option></select></label><label>Tindak lanjut<input name="follow_up"></label><label>Catatan<textarea name="teacher_notes"></textarea></label><button class="button primary">Simpan Setoran</button></form></section>
<section class="card"><h2>Catat Murāja‘ah</h2><form class="stack compact" method="post" action="{{ route('teacher.meetings.murajaah.store',$meeting) }}">@csrf<label>Santri<select name="student_id" required><option value="">Pilih</option>@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->full_name }}</option>@endforeach</select></label><label>Jenis<select name="murajaah_type"><option value="scheduled">Terjadwal</option><option value="random_recall">Pemanggilan Acak</option><option value="continuation">Sambung Ayat</option><option value="tasmi">Tasmi‘</option><option value="home">Di Rumah</option></select></label><label>Surah<select name="surah_id" required>@foreach($surahs as $surah)<option value="{{ $surah->id }}">{{ $surah->id }}. {{ $surah->name_latin }}</option>@endforeach</select></label><div class="form-grid"><label>Ayat awal<input type="number" name="start_verse" min="1" required></label><label>Ayat akhir<input type="number" name="end_verse" min="1" required></label></div><label>Hasil<select name="result"><option value="maintained">Masih Terjaga</option><option value="strengthening_needed">Perlu Dikuatkan</option><option value="reactivation_needed">Perlu Dihidupkan Kembali</option></select></label><label>Bantuan<select name="assistance_level"><option value="none">Tanpa Bantuan</option><option value="little">Sedikit Bantuan</option><option value="several">Beberapa Kali Bantuan</option><option value="much">Banyak Bantuan</option></select></label><label>Jadwalkan ulang<input type="date" name="next_review_date"></label><label>Catatan<textarea name="teacher_notes"></textarea></label><button class="button primary">Simpan Murāja‘ah</button></form></section>
</div>
@if($meeting->status!=='completed')<section class="card finish-card"><div><h2>Selesaikan pertemuan</h2><p>Pastikan absensi tersimpan. Tugas rumah tidak wajib dibuat.</p></div><form method="post" action="{{ route('teacher.meetings.finish',$meeting) }}">@csrf @method('PUT')<textarea name="general_notes" placeholder="Catatan umum, opsional"></textarea><button class="button primary">Selesaikan Pertemuan</button></form></section>@endif
@endsection
