<?php

return [
    'eyebrow' => 'IMPLEMENTASI PERTAMA SULLAMUL ḤIFẒ',
    'name' => 'TPA Al-Insyirah',
    'descriptor' => 'Masjid & Taman Pendidikan Al-Qur’an',
    'brand_relation' => 'TPA Al-Insyirah — Powered by Sullamul Ḥifẓ',
    'headline' => 'Rumah Qur’an, tempat tumbuhnya generasi mulia.',
    'summary' => 'TPA Al-Insyirah menjadi tempat implementasi pertama Sullamul Ḥifẓ. Pembinaan memadukan tahsīn, tahfizh, murāja‘ah, adab, keterlibatan keluarga, dan pencatatan perkembangan yang manusiawi.',
    'reference_note' => 'Profil ini disusun sebagai contoh implementasi. Lembaga lain dapat menyalin strukturnya, tetapi wajib menyesuaikan identitas hukum, kepemimpinan, jadwal, kurikulum, kapasitas, biaya, dan kebijakan perlindungan anak.',
    'identity' => [
        'code' => 'ALINSYIRAH',
        'slug' => 'alinsyirah',
        'academic_year' => '2026/2027',
        'timezone' => 'Asia/Jakarta',
        'implementation_status' => 'Pilot project / implementasi pertama',
        'address' => null,
        'phone' => null,
        'email' => null,
        'leader_name' => null,
        'legal_name' => null,
    ],
    'stats' => [
        ['value' => '88', 'label' => 'Santri aktif awal'],
        ['value' => '6', 'label' => 'Kelas utama'],
        ['value' => '2', 'label' => 'Kelompok Tahfizh'],
        ['value' => '4', 'label' => 'Guru awal'],
    ],
    'vision' => [
        'label' => 'Arah visi pengembangan',
        'status' => 'Draft referensi — perlu disahkan lembaga',
        'text' => 'Menjadi ekosistem pendidikan keluarga yang menuntun anak dan orang tua bertumbuh bersama Al-Qur’an secara bertahap, personal, terukur, manusiawi, dan berkelanjutan.',
    ],
    'outcomes' => [
        ['title' => 'Kuat bacaan', 'description' => 'Tahsīn dibina melalui talaqqi, latihan, koreksi, dan pengulangan yang sesuai kebutuhan santri.'],
        ['title' => 'Kuat hafalan', 'description' => 'Hafalan baru tidak dipisahkan dari murāja‘ah, pemanggilan kembali, dan penjagaan setelah setoran.'],
        ['title' => 'Kuat pemahaman', 'description' => 'Ayat didekatkan kepada makna dan kehidupan sesuai usia, kesiapan, serta konteks pembinaan.'],
        ['title' => 'Kuat pengamalan', 'description' => 'Nilai Al-Qur’an dihidupkan melalui adab, kebiasaan, tugas keluarga, dan keteladanan.'],
        ['title' => 'Kuat istiqamah', 'description' => 'Perjalanan dijaga agar santri dapat melanjutkan, menyesuaikan beban, dan kembali ketika ritme berubah.'],
    ],
    'classes' => [
        ['name' => 'Tamhidi A', 'students' => 18, 'schedule' => '13.00–15.00 WIB', 'teacher' => 'Nurul', 'focus' => 'Pembelajaran dasar dan tahsīn'],
        ['name' => 'Tamhidi B', 'students' => 13, 'schedule' => '13.00–15.00 WIB', 'teacher' => 'Nurul', 'focus' => 'Pembelajaran dasar dan tahsīn'],
        ['name' => 'Mustawa Awal A', 'students' => 16, 'schedule' => '15.30–17.30 WIB', 'teacher' => 'Jundi', 'focus' => 'Tahsīn'],
        ['name' => 'Mustawa Awal B', 'students' => 14, 'schedule' => '15.30–17.30 WIB', 'teacher' => 'Jundi', 'focus' => 'Tahsīn'],
        ['name' => 'Mustawa Tsani A', 'students' => 14, 'schedule' => '15.30–17.30 WIB', 'teacher' => 'Yanti', 'focus' => 'Tahsīn'],
        ['name' => 'Mustawa Tsani B', 'students' => 13, 'schedule' => '15.30–17.30 WIB', 'teacher' => 'Yanti', 'focus' => 'Tahsīn'],
    ],
    'learning_groups' => [
        ['name' => 'Tahfizh A', 'students' => 30, 'teacher' => 'Sofyan', 'source_classes' => ['Mustawa Awal A', 'Mustawa Tsani A'], 'session' => 'Sesi pertama'],
        ['name' => 'Tahfizh B', 'students' => 27, 'teacher' => 'Sofyan', 'source_classes' => ['Mustawa Awal B', 'Mustawa Tsani B'], 'session' => 'Sesi kedua'],
    ],
    'teachers' => [
        ['name' => 'Nurul', 'role' => 'Pengampu Tamhidi', 'assignment' => 'Tamhidi A dan Tamhidi B'],
        ['name' => 'Jundi', 'role' => 'Pengampu Tahsīn Mustawa Awal', 'assignment' => 'Mustawa Awal A dan Mustawa Awal B'],
        ['name' => 'Yanti', 'role' => 'Pengampu Tahsīn Mustawa Tsani', 'assignment' => 'Mustawa Tsani A dan Mustawa Tsani B'],
        ['name' => 'Sofyan', 'role' => 'Pengampu Tahfizh', 'assignment' => 'Tahfizh A dan Tahfizh B'],
    ],
    'programs' => [
        'core' => [
            ['title' => 'Pembelajaran TPA', 'description' => 'Kegiatan kelas bertahap sesuai jenjang dan kebutuhan perkembangan santri.'],
            ['title' => 'Tahsīn', 'description' => 'Perbaikan bacaan, makhraj, tajwid, kelancaran, dan adab membaca Al-Qur’an.'],
            ['title' => 'Tahfizh', 'description' => 'Hafalan baru dengan target yang dapat disesuaikan dan tidak digunakan untuk ranking.'],
            ['title' => 'Murāja‘ah', 'description' => 'Penjagaan hafalan lama melalui pengulangan, pemanggilan kembali, dan evaluasi berkala.'],
            ['title' => 'Pembinaan Jumat', 'description' => 'Materi nilai, aktivitas keluarga, tindak lanjut, dan dokumentasi pembinaan.'],
        ],
        'enrichment' => [
            ['title' => 'Public Speaking', 'status' => 'Referensi pengembangan'],
            ['title' => 'Menggambar', 'status' => 'Referensi pengembangan'],
            ['title' => 'Futsal', 'status' => 'Referensi pengembangan'],
        ],
    ],
    'learning_path' => [
        ['step' => '01', 'title' => 'Kenali', 'description' => 'Kenali kondisi bacaan, hafalan, kesiapan, kebiasaan, dan dukungan keluarga.'],
        ['step' => '02', 'title' => 'Tetapkan pijakan', 'description' => 'Guru menentukan kelas, kelompok, target, dan beban yang masuk akal.'],
        ['step' => '03', 'title' => 'Dampingi', 'description' => 'Pembinaan berlangsung melalui talaqqi, latihan, keteladanan, tugas, dan komunikasi.'],
        ['step' => '04', 'title' => 'Catat seperlunya', 'description' => 'Aplikasi mencatat jejak penting tanpa mengubah guru menjadi operator data penuh waktu.'],
        ['step' => '05', 'title' => 'Jaga dan lanjutkan', 'description' => 'Hasil ditinjau bersama agar bacaan, hafalan, adab, dan keterlibatan keluarga tetap berlanjut.'],
    ],
    'values' => [
        ['title' => 'Cinta Al-Qur’an', 'description' => 'Membaca, menghafal, memahami, dan menjaga dengan penuh cinta.'],
        ['title' => 'Akhlak Mulia', 'description' => 'Taat, jujur, sopan, disiplin, dan bertanggung jawab.'],
        ['title' => 'Ilmu Bermanfaat', 'description' => 'Rajin belajar dan menggunakan ilmu untuk menghadirkan kebaikan.'],
        ['title' => 'Masjid Rumah Kita', 'description' => 'Menjaga kebersihan, ketertiban, dan rasa memiliki terhadap masjid.'],
        ['title' => 'Bersama Membangun Kebaikan', 'description' => 'Menghormati, menyayangi, dan tidak saling menyakiti.'],
    ],
    'family_partnership' => [
        ['title' => 'Informasi yang terbaca', 'description' => 'Orang tua melihat jadwal, kehadiran, tugas, perkembangan, dan pengumuman yang relevan.'],
        ['title' => 'Tugas yang manusiawi', 'description' => 'Bukti tugas dapat berupa checklist, audio, video, foto, atau tanggapan singkat sesuai kebutuhan.'],
        ['title' => 'Buku penghubung privat', 'description' => 'Guru dan wali berkomunikasi dalam ruang privat yang terkait dengan kebutuhan santri.'],
        ['title' => 'Tanpa budaya ranking', 'description' => 'Laporan menampilkan perkembangan dan kebutuhan, bukan perbandingan antarsantri.'],
    ],
    'principles' => [
        ['title' => 'Human Before Data', 'description' => 'Santri dipandang sebagai manusia yang bertumbuh, bukan kumpulan angka.'],
        ['title' => 'No Ranking Culture', 'description' => 'Tidak ada peringkat berdasarkan jumlah hafalan, kecepatan, nilai gabungan, atau profil belajar.'],
        ['title' => 'Flexible but Structured', 'description' => 'Kelas, program, metode, dan beban dapat berbeda, tetapi istilah serta standar dasar tetap konsisten.'],
        ['title' => 'Pembinaan nyata lebih utama', 'description' => 'Aplikasi membantu pencatatan dan komunikasi, bukan menggantikan guru, orang tua, talaqqi, dan keteladanan.'],
    ],
    'reference' => [
        'copyable' => [
            'Struktur profil lembaga dan hubungan dengan master brand.',
            'Pemisahan kelas utama dengan kelompok pembelajaran lintas kelas.',
            'Tahun ajaran, penugasan guru, jadwal, dan riwayat keanggotaan.',
            'Pencatatan tahsīn, tahfizh, murāja‘ah, kehadiran, tugas, dan komunikasi.',
            'Ikrar santri, budaya bersama, Pembinaan Jumat, dan kemitraan keluarga.',
            'Prinsip tanpa ranking, privasi anak, moderasi, dan pencatatan seperlunya.',
        ],
        'must_adapt' => [
            'Nama hukum, izin, alamat, kontak, penanggung jawab, dan struktur organisasi.',
            'Visi, misi, kurikulum, kalender, jadwal, biaya, kapasitas, dan aturan penerimaan.',
            'Pembagian guru, kelas, program, target pembelajaran, dan standar evaluasi.',
            'Kebijakan perlindungan anak, dokumentasi foto/video, retensi file, dan hak akses.',
            'Kondisi masjid, masyarakat, keluarga, budaya lokal, serta sumber daya lembaga.',
        ],
        'steps' => [
            ['number' => '1', 'title' => 'Tetapkan identitas', 'description' => 'Lengkapi identitas resmi dan pihak yang bertanggung jawab.'],
            ['number' => '2', 'title' => 'Petakan operasional', 'description' => 'Daftar kelas, program, jadwal, guru, santri, wali, dan alur kerja nyata.'],
            ['number' => '3', 'title' => 'Pilih fitur minimum', 'description' => 'Mulai dari masalah paling penting; hindari memasukkan seluruh fitur sekaligus.'],
            ['number' => '4', 'title' => 'Uji bersama pengguna', 'description' => 'Libatkan admin, guru, dan wali dalam pilot terbatas.'],
            ['number' => '5', 'title' => 'Perbaiki lalu perluas', 'description' => 'Gunakan temuan pilot untuk menyederhanakan formulir, bahasa, dan laporan.'],
        ],
    ],
    'placeholders' => [
        'Alamat lengkap',
        'Nomor telepon dan WhatsApp resmi',
        'Email lembaga',
        'Nama kepala atau penanggung jawab',
        'Nama hukum dan nomor legalitas',
        'Logo resmi lembaga dalam format digital',
        'Visi dan misi yang telah disahkan',
        'Biaya, kuota, kalender, dan ketentuan penerimaan',
    ],
    'poster_image' => '/images/tpa-al-insyirah/ikrar-santri-reference.png',
];
