@extends('layouts.app')
@php
    $pageTitle='Website Publik';
@endphp
@section('content')
<div class="page-head"><div><span class="eyebrow">CMS RINGAN</span><h1>Website publik</h1><p>Kelola halaman, artikel, dan pendaftaran tanpa mengubah source.</p></div><a class="button secondary" target="_blank" href="{{ route('public.home') }}">Buka website</a></div>
<div class="grid two">
<form class="card stack" method="post" action="{{ route('admin.website.pages.store') }}">@csrf<h2>Tambah halaman</h2><div class="form-grid"><label>Slug<input name="slug" placeholder="contoh: metode-kuat" required></label><label>Judul<input name="title" required></label><label class="span-2">Ringkasan<textarea name="summary"></textarea></label><label class="span-2">Isi<textarea name="content" rows="10"></textarea></label><label>Status<select name="status"><option value="published">Terbit</option><option value="draft">Draft</option></select></label><label>Urutan<input type="number" name="sort_order" value="0"></label></div><button class="button primary">Tambah halaman</button></form>
<form class="card stack" method="post" enctype="multipart/form-data" action="{{ route('admin.website.articles.store') }}">@csrf<h2>Tulis artikel</h2><div class="form-grid"><label>Judul<input name="title" required></label><label>Slug opsional<input name="slug"></label><label class="span-2">Ringkasan<textarea name="excerpt"></textarea></label><label class="span-2">Isi artikel<textarea name="content" rows="10" required></textarea></label><label>Status<select name="status"><option value="draft">Draft</option><option value="published">Terbit</option></select></label><label>Tanggal terbit<input type="datetime-local" name="published_at"></label><label class="span-2">Gambar sampul<input type="file" name="cover_image" accept="image/*"></label></div><button class="button primary">Simpan artikel</button></form>
</div>
<div class="grid two">
<div class="card"><h2>Halaman tersimpan</h2><div class="cards-list">@forelse($pages as $page)<details><summary>{{ $page->title }} <span class="badge">{{ $page->status }}</span></summary><form class="stack compact" method="post" action="{{ route('admin.website.pages.update',$page) }}">@csrf @method('put')<label>Judul<input name="title" value="{{ $page->title }}"></label><label>Ringkasan<textarea name="summary">{{ $page->summary }}</textarea></label><label>Isi<textarea name="content" rows="8">{{ $page->content }}</textarea></label><label>Status<select name="status"><option value="published" @selected($page->status==='published')>Terbit</option><option value="draft" @selected($page->status==='draft')>Draft</option></select></label><input type="hidden" name="sort_order" value="{{ $page->sort_order }}"><button class="button small">Perbarui</button></form></details>@empty<p class="empty">Belum ada halaman database; halaman bawaan tetap tampil.</p>@endforelse</div></div>
<div class="card"><h2>Artikel</h2><div class="cards-list">@forelse($articles as $article)<details><summary>{{ $article->title }} <span class="badge">{{ $article->status }}</span></summary><form class="stack compact" method="post" enctype="multipart/form-data" action="{{ route('admin.website.articles.update',$article) }}">@csrf @method('put')<label>Judul<input name="title" value="{{ $article->title }}"></label><label>Ringkasan<textarea name="excerpt">{{ $article->excerpt }}</textarea></label><label>Isi<textarea name="content" rows="8">{{ $article->content }}</textarea></label><label>Status<select name="status"><option value="draft" @selected($article->status==='draft')>Draft</option><option value="published" @selected($article->status==='published')>Terbit</option></select></label><input type="hidden" name="published_at" value="{{ optional($article->published_at)->format('Y-m-d\TH:i') }}"><button class="button small">Perbarui</button></form></details>@empty<p class="empty">Belum ada artikel.</p>@endforelse</div>{{ $articles->links() }}</div>
</div>
<div class="card"><h2>Pendaftaran masuk</h2><div class="card table-card"><table><thead><tr><th>Calon santri</th><th>Wali</th><th>Program</th><th>Status</th></tr></thead><tbody>@forelse($registrations as $registration)<tr><td><strong>{{ $registration->student_name }}</strong><small>{{ $registration->student_age }}</small></td><td>{{ $registration->guardian_name }}<small>{{ $registration->guardian_phone }} · {{ $registration->guardian_email }}</small></td><td>{{ $registration->desired_program ?: '-' }}</td><td><form method="post" action="{{ route('admin.website.registrations.update',$registration) }}">@csrf @method('put')<select name="status" onchange="this.form.submit()">@foreach(['new','contacted','scheduled','accepted','rejected','closed'] as $status)<option value="{{ $status }}" @selected($registration->status===$status)>{{ $status }}</option>@endforeach</select></form></td></tr>@empty<tr><td colspan="4" class="empty">Belum ada pendaftaran.</td></tr>@endforelse</tbody></table></div>{{ $registrations->links() }}</div>
@endsection
