@extends('layouts.app',['pageTitle'=>'Academic Core'])
@section('content')
<div class="page-head"><div><span class="eyebrow">V1.5.0 ACADEMIC CORE</span><h1>Fondasi Akademik</h1><p>{{ $activeYear?->name ?? 'Belum ada tahun ajaran aktif' }} · target, rubu’, marhalah, observasi, dan kesiapan lembaga.</p></div><div class="actions"><a class="button secondary" href="{{ route('admin.institution.edit') }}">Profil lembaga</a><a class="button secondary" href="{{ route('admin.academic.index') }}">Kelas & jadwal</a></div></div>
<div class="stats-grid four">
<div class="stat-card"><span>Target aktif</span><strong>{{ $activeTargetCount }}</strong></div>
<div class="stat-card"><span>Target selesai</span><strong>{{ $completedTargetCount }}</strong></div>
<div class="stat-card"><span>Observasi belajar</span><strong>{{ $observationCount }}</strong></div>
<div class="stat-card"><span>STIFIn belum dites</span><strong>{{ $untestedStifinCount }}</strong></div>
</div>
<div class="grid two">
<section class="card"><h2>Tahun ajaran aktif</h2>@if($activeYear)<form class="stack compact" method="post" action="{{ route('admin.academic-core.year.update',$activeYear) }}">@csrf @method('PUT')<label>Tahun ajaran<input value="{{ $activeYear->name }}" disabled></label><label>Semester aktif<select name="active_semester"><option value="semester_1" @selected($activeYear->active_semester==='semester_1')>Semester 1</option><option value="semester_2" @selected($activeYear->active_semester==='semester_2')>Semester 2</option><option value="antara_semester" @selected($activeYear->active_semester==='antara_semester')>Antara Semester</option></select></label><label>Status pendaftaran<select name="enrollment_status"><option value="closed" @selected($activeYear->enrollment_status==='closed')>Ditutup</option><option value="open" @selected($activeYear->enrollment_status==='open')>Dibuka</option><option value="internal_only" @selected($activeYear->enrollment_status==='internal_only')>Internal</option></select></label><button class="button primary">Simpan pengaturan tahun</button></form>@else<p class="empty">Aktifkan tahun ajaran melalui menu Akademik terlebih dahulu.</p>@endif</section>
<section class="card"><h2>Kesiapan lembaga</h2><div class="cards-list"><div class="item-card static"><div><strong>Identitas</strong><small>{{ $institution->name }} · {{ $institution->setting('tagline','Bukan Sekadar Hafal, Tapi KUAT') }}</small></div></div><div class="item-card static"><div><strong>Profil resmi</strong><small>{{ $institution->setting('profile_completed',false) ? 'Sudah lengkap' : 'Alamat, kontak, penanggung jawab, visi atau misi masih perlu dilengkapi' }}</small></div></div><div class="item-card static"><div><strong>Prinsip</strong><small>Human Before Data · No Ranking Culture · Rubu’ sebagai milestone, bukan label.</small></div></div></div></section>
</div>
<div class="grid two">
<section class="card"><h2>Buat target hafalan</h2><p class="hint">Admin dapat membuat target untuk santri. Guru juga memiliki ruang target sendiri.</p>@if($activeYear)<form class="stack compact" method="post" action="{{ route('admin.academic-core.targets.store') }}">@csrf<label>Santri<select name="student_id" required><option value="">Pilih santri</option>@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->full_name }} — {{ $student->currentEnrollment?->schoolClass?->name ?? 'Belum ada kelas' }}</option>@endforeach</select></label><label>Milestone Juz 30 (opsional)<select name="quran_rubu_id"><option value="">Belum ditentukan</option>@foreach($rubus as $rubu)<option value="{{ $rubu->id }}">{{ $rubu->name }}</option>@endforeach</select></label><label>Surah<select name="surah_id" required>@foreach($surahs as $surah)<option value="{{ $surah->id }}">{{ $surah->id }}. {{ $surah->name_latin }}</option>@endforeach</select></label><div class="form-grid"><label>Ayat awal<input type="number" name="start_verse" min="1" required></label><label>Ayat akhir<input type="number" name="end_verse" min="1" required></label></div><div class="form-grid"><label>Marhalah<select name="marhalah_type_id"><option value="">Belum ditentukan</option>@foreach($marhalah as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select></label><label>Jenis target<select name="target_type"><option value="new_memorization">Hafalan baru</option><option value="initial_repetition">Pengulangan awal</option><option value="murajaah">Murāja‘ah</option><option value="tasmi">Tasmi‘</option><option value="exam">Ujian</option></select></label></div><div class="form-grid"><label>Tanggal mulai<input type="date" name="target_date" value="{{ now()->format('Y-m-d') }}"></label><label>Batas waktu<input type="date" name="due_date"></label></div><label>Catatan<textarea name="notes" rows="3"></textarea></label><button class="button primary">Simpan target</button></form>@else<p class="empty">Belum dapat membuat target tanpa tahun ajaran aktif.</p>@endif</section>
<section class="card"><h2>Delapan rubu’ Juz 30</h2><p class="hint">Rubu’ adalah milestone penjagaan, bukan marhalah atau ranking.</p><div class="cards-list">@foreach($rubus as $rubu)<div class="item-card static"><div><strong>{{ $rubu->name }}</strong><small>Surat {{ $rubu->start_surah_id }} sampai {{ $rubu->end_surah_id }}</small></div><span>{{ $rubu->rubu_number }}/8</span></div>@endforeach</div></section>
</div>
<section class="card"><div class="section-head"><div><h2>Target terbaru</h2><p class="hint">Riwayat tidak ditimpa; setiap target memiliki statusnya sendiri.</p></div><span>{{ $targets->count() }} ditampilkan</span></div>@forelse($targets as $target)<div class="list-row"><div><strong>{{ $target->student->full_name }} · {{ $target->surah->name_latin }} {{ $target->start_verse }}–{{ $target->end_verse }}</strong><small>{{ $target->rubu?->name ?? 'Rubu belum dipilih' }} · {{ $target->marhalah?->name ?? 'Marhalah belum dipilih' }} · {{ str_replace('_',' ',$target->status) }}</small><p>{{ $target->notes }}</p></div><form class="inline-form" method="post" action="{{ route('admin.academic-core.targets.update',$target) }}">@csrf @method('PUT')<select name="status"><option value="active" @selected($target->status==='active')>Aktif</option><option value="in_progress" @selected($target->status==='in_progress')>Berjalan</option><option value="strengthening" @selected($target->status==='strengthening')>Penguatan</option><option value="completed" @selected($target->status==='completed')>Selesai</option><option value="paused" @selected($target->status==='paused')>Jeda</option><option value="cancelled" @selected($target->status==='cancelled')>Dibatalkan</option></select><input type="hidden" name="notes" value="{{ $target->notes }}"><button class="button small secondary">Simpan</button></form></div>@empty<p class="empty">Belum ada target hafalan.</p>@endforelse</section>
@endsection
