@extends('layouts.app')
@php($pageTitle='Profil Wali')
@section('content')
<div class="page-head"><div><span class="eyebrow">WALI SANTRI</span><h1>{{ $guardian->full_name }}</h1><p>{{ $guardian->students->count() }} santri terhubung.</p></div><a class="button secondary" href="{{ route('admin.guardians.index') }}">Kembali</a></div>
<div class="grid two"><form class="card stack" method="post" action="{{ route('admin.guardians.update',$guardian) }}">@csrf @method('put')
<h2>Profil wali</h2><label>Nama<input name="full_name" value="{{ old('full_name',$guardian->full_name) }}" required></label><label>Nomor telepon<input name="phone" value="{{ old('phone',$guardian->phone) }}"></label><label>Email<input type="email" name="email" value="{{ old('email',$guardian->email) }}"></label><label>Pekerjaan<input name="occupation" value="{{ old('occupation',$guardian->occupation) }}"></label><label>Alamat<textarea name="address">{{ old('address',$guardian->address) }}</textarea></label><label>Status<select name="status"><option value="active" @selected($guardian->status==='active')>Aktif</option><option value="inactive" @selected($guardian->status==='inactive')>Nonaktif</option></select></label><button class="button primary">Simpan</button></form>
<div class="stack"><div class="card"><h2>Santri terhubung</h2><div class="cards-list">@foreach($guardian->students as $student)<a class="item-card" href="{{ route('admin.students.show',$student) }}"><span><strong>{{ $student->full_name }}</strong><small>{{ $student->currentEnrollment?->schoolClass?->name }}</small></span><span class="badge">{{ $student->pivot->relationship }}</span></a>@endforeach</div></div>
@if($guardian->user)<div class="card stack"><h2>Aktivasi akun</h2><p class="muted">Buat tautan pribadi yang berlaku 48 jam. Email akan dikirim otomatis bila alamat email tersedia.</p><form method="post" action="{{ route('admin.accounts.invitation',$guardian->user) }}">@csrf<button class="button secondary" type="submit">Buat Tautan Aktivasi</button></form></div><form class="card stack" method="post" action="{{ route('admin.accounts.password',$guardian->user) }}">@csrf @method('put')<h2>Reset kata sandi</h2><label>Password baru<input type="password" name="password" minlength="12" required></label><label>Ulangi password<input type="password" name="password_confirmation" minlength="12" required></label><button class="button danger">Atur ulang</button></form>@endif</div></div>
@endsection
